# 팀원용 데이터베이스 접속 정보
# 외부 접속용 설정

[mysql]
db_host = "123.212.212.221"           # 공인 IP
db_port = 3306
db_user = "solux"                     # 팀 공용 사용자
db_password = "1118"                  # 팀 공용 비밀번호
db_name = "solux_finance"             # 데이터베이스 이름

# 사용법:
# 1. 이 파일을 .streamlit/secrets.toml로 복사
# 2. 또는 환경 변수로 설정
# 3. 앱 실행: streamlit run app.py
